cc_library(name = 'base',
           srcs = [
                   'at_exit.cc',
                   'atomicops_internals_x86_gcc.cc',
                   'counter.cc',
                   'debug_util.cc',
                   'demangle.cc',
                   'dmg_fp.cc',
                   'dynamic_annotations.c',
                   'env.cc',
                   'env.cc',
                   'flags.cc',
                   'flags_reporting.cc',
                   'hash.cc',
                   'icu_utf.cc',
                   'lazy_instance.cc',
                   'logging.cc',
                   'net.cc',
                   'platform_thread_posix.cc',
                   'prtime.cc',
                   'safe_strerror_posix.cc',
                   'string16.cc',
                   'string_piece.cc',
                   'string_util.cc',
                   'symbolize.cc',
                   'thread.cc',
                   'thread_local_posix.cc',
                   'thread_pool.cc',
                   'thread_restrictions.cc',
                   'time.cc',
                   'utf.cc',
                   'utf_string_conversion_utils.cc',
                   'utf_string_conversions.cc',
                  ],
           deps = [],  # base should not depends on other components!
           copt = ['no_style_check']
           )
